/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artist {
  'id' : Principal,
  'stripeAccountId' : string,
  'name' : string,
}
export interface Item {
  'id' : bigint,
  'title' : string,
  'artistId' : Principal,
  'description' : string,
  'category' : ItemCategory,
  'price' : bigint,
  'fileIds' : Array<string>,
}
export type ItemCategory = { 'music' : null } |
  { 'other' : null } |
  { 'video' : null } |
  { 'ceramic' : null } |
  { 'painting' : null } |
  { 'threeDPrint' : null };
export interface PurchaseRecord {
  'id' : bigint,
  'status' : PurchaseStatus,
  'item' : Item,
  'seller' : Artist,
  'platformCommission' : bigint,
  'artistShare' : bigint,
  'buyer' : Principal,
  'amount' : bigint,
}
export type PurchaseStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteBranding {
  'primaryColor' : string,
  'name' : string,
  'logoId' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArtist' : ActorMethod<[string, string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createItem' : ActorMethod<
    [string, ItemCategory, bigint, string, Array<string>],
    undefined
  >,
  'getAllArtists' : ActorMethod<[], Array<Artist>>,
  'getAllArtistsAndTransactions' : ActorMethod<
    [],
    {
      'artists' : Array<Artist>,
      'purchases' : Array<PurchaseRecord>,
      'items' : Array<Item>,
    }
  >,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getAllPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getArtist' : ActorMethod<[Principal], Artist>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommissionRate' : ActorMethod<[], number>,
  'getItem' : ActorMethod<[bigint], Item>,
  'getItemsByArtist' : ActorMethod<[Principal], Array<Item>>,
  'getItemsByCategory' : ActorMethod<[ItemCategory], Array<Item>>,
  'getPurchase' : ActorMethod<[bigint], PurchaseRecord>,
  'getPurchasesByUser' : ActorMethod<[Principal], Array<PurchaseRecord>>,
  'getRevenueStats' : ActorMethod<
    [],
    {
      'totalCommission' : bigint,
      'totalSales' : bigint,
      'totalArtistShare' : bigint,
    }
  >,
  'getSiteBranding' : ActorMethod<[], SiteBranding>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTermsAndConditions' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processPurchase' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArtist' : ActorMethod<[string, string], undefined>,
  'updateCommissionRate' : ActorMethod<[number], undefined>,
  'updateItem' : ActorMethod<
    [bigint, string, ItemCategory, bigint, string, Array<string>],
    undefined
  >,
  'updateSiteBranding' : ActorMethod<[string, string, string], undefined>,
  'updateTermsAndConditions' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];