/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ItemCategory = IDL.Variant({
  'music' : IDL.Null,
  'other' : IDL.Null,
  'video' : IDL.Null,
  'ceramic' : IDL.Null,
  'painting' : IDL.Null,
  'threeDPrint' : IDL.Null,
});
export const Artist = IDL.Record({
  'id' : IDL.Principal,
  'stripeAccountId' : IDL.Text,
  'name' : IDL.Text,
});
export const PurchaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'artistId' : IDL.Principal,
  'description' : IDL.Text,
  'category' : ItemCategory,
  'price' : IDL.Nat,
  'fileIds' : IDL.Vec(IDL.Text),
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : PurchaseStatus,
  'item' : Item,
  'seller' : Artist,
  'platformCommission' : IDL.Nat,
  'artistShare' : IDL.Nat,
  'buyer' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteBranding = IDL.Record({
  'primaryColor' : IDL.Text,
  'name' : IDL.Text,
  'logoId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArtist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createItem' : IDL.Func(
      [IDL.Text, ItemCategory, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'getAllArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
  'getAllArtistsAndTransactions' : IDL.Func(
      [],
      [
        IDL.Record({
          'artists' : IDL.Vec(Artist),
          'purchases' : IDL.Vec(PurchaseRecord),
          'items' : IDL.Vec(Item),
        }),
      ],
      ['query'],
    ),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
  'getArtist' : IDL.Func([IDL.Principal], [Artist], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommissionRate' : IDL.Func([], [IDL.Float64], ['query']),
  'getItem' : IDL.Func([IDL.Nat], [Item], ['query']),
  'getItemsByArtist' : IDL.Func([IDL.Principal], [IDL.Vec(Item)], ['query']),
  'getItemsByCategory' : IDL.Func([ItemCategory], [IDL.Vec(Item)], ['query']),
  'getPurchase' : IDL.Func([IDL.Nat], [PurchaseRecord], ['query']),
  'getPurchasesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PurchaseRecord)],
      ['query'],
    ),
  'getRevenueStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCommission' : IDL.Nat,
          'totalSales' : IDL.Nat,
          'totalArtistShare' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSiteBranding' : IDL.Func([], [SiteBranding], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTermsAndConditions' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'processPurchase' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateArtist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCommissionRate' : IDL.Func([IDL.Float64], [], []),
  'updateItem' : IDL.Func(
      [IDL.Nat, IDL.Text, ItemCategory, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateSiteBranding' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTermsAndConditions' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ItemCategory = IDL.Variant({
    'music' : IDL.Null,
    'other' : IDL.Null,
    'video' : IDL.Null,
    'ceramic' : IDL.Null,
    'painting' : IDL.Null,
    'threeDPrint' : IDL.Null,
  });
  const Artist = IDL.Record({
    'id' : IDL.Principal,
    'stripeAccountId' : IDL.Text,
    'name' : IDL.Text,
  });
  const PurchaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
  });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'artistId' : IDL.Principal,
    'description' : IDL.Text,
    'category' : ItemCategory,
    'price' : IDL.Nat,
    'fileIds' : IDL.Vec(IDL.Text),
  });
  const PurchaseRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : PurchaseStatus,
    'item' : Item,
    'seller' : Artist,
    'platformCommission' : IDL.Nat,
    'artistShare' : IDL.Nat,
    'buyer' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteBranding = IDL.Record({
    'primaryColor' : IDL.Text,
    'name' : IDL.Text,
    'logoId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArtist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createItem' : IDL.Func(
        [IDL.Text, ItemCategory, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'getAllArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
    'getAllArtistsAndTransactions' : IDL.Func(
        [],
        [
          IDL.Record({
            'artists' : IDL.Vec(Artist),
            'purchases' : IDL.Vec(PurchaseRecord),
            'items' : IDL.Vec(Item),
          }),
        ],
        ['query'],
      ),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'getArtist' : IDL.Func([IDL.Principal], [Artist], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommissionRate' : IDL.Func([], [IDL.Float64], ['query']),
    'getItem' : IDL.Func([IDL.Nat], [Item], ['query']),
    'getItemsByArtist' : IDL.Func([IDL.Principal], [IDL.Vec(Item)], ['query']),
    'getItemsByCategory' : IDL.Func([ItemCategory], [IDL.Vec(Item)], ['query']),
    'getPurchase' : IDL.Func([IDL.Nat], [PurchaseRecord], ['query']),
    'getPurchasesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'getRevenueStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCommission' : IDL.Nat,
            'totalSales' : IDL.Nat,
            'totalArtistShare' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSiteBranding' : IDL.Func([], [SiteBranding], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTermsAndConditions' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'processPurchase' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateArtist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCommissionRate' : IDL.Func([IDL.Float64], [], []),
    'updateItem' : IDL.Func(
        [IDL.Nat, IDL.Text, ItemCategory, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateSiteBranding' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTermsAndConditions' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };